//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitsLauncher.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecruitsLauncher.Resources.Localization.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY OFFLINE.
        /// </summary>
        internal static string actionBtnOffline {
            get {
                return ResourceManager.GetString("actionBtnOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY NOW.
        /// </summary>
        internal static string actionBtnOnline {
            get {
                return ResourceManager.GetString("actionBtnOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        internal static string actionBtnSignIn {
            get {
                return ResourceManager.GetString("actionBtnSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting Login....
        /// </summary>
        internal static string attemptingSignIn {
            get {
                return ResourceManager.GetString("attemptingSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOAD.
        /// </summary>
        internal static string downloadBtn {
            get {
                return ResourceManager.GetString("downloadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Update.
        /// </summary>
        internal static string downloadingUpdate {
            get {
                return ResourceManager.GetString("downloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Info.
        /// </summary>
        internal static string incorrectInfo {
            get {
                return ResourceManager.GetString("incorrectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Update....
        /// </summary>
        internal static string initializingUpdate {
            get {
                return ResourceManager.GetString("initializingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Run Repair to Verify and Fix your game Installation.
        /// </summary>
        internal static string launchError_p1 {
            get {
                return ResourceManager.GetString("launchError_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the Problem Persists, Please Reinstall Recruits or Redownload the Launcher..
        /// </summary>
        internal static string launchError_p2 {
            get {
                return ResourceManager.GetString("launchError_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Ok to Run Repair Now..
        /// </summary>
        internal static string launchError_p3 {
            get {
                return ResourceManager.GetString("launchError_p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting Download.
        /// </summary>
        internal static string needDownload {
            get {
                return ResourceManager.GetString("needDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Account Does Not Own Recruits.
        /// </summary>
        internal static string noOwn {
            get {
                return ResourceManager.GetString("noOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Requires Administrative Privileges to Install to. Please change Install Directory in the Options Menu, or press Ok to restart with Administrative Privileges..
        /// </summary>
        internal static string privError_p1 {
            get {
                return ResourceManager.GetString("privError_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Connecting To Server! Retrying Connection in .
        /// </summary>
        internal static string retryTXT_p1 {
            get {
                return ResourceManager.GetString("retryTXT_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning For Game Install....
        /// </summary>
        internal static string scanningInstall {
            get {
                return ResourceManager.GetString("scanningInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Seconds.
        /// </summary>
        internal static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE AVAILABLE.
        /// </summary>
        internal static string updateAvailable {
            get {
                return ResourceManager.GetString("updateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Complete!.
        /// </summary>
        internal static string updateComplete {
            get {
                return ResourceManager.GetString("updateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Game Is Up To Date.
        /// </summary>
        internal static string updated {
            get {
                return ResourceManager.GetString("updated", resourceCulture);
            }
        }
    }
}
